version: '3'
services:
    # busybox:
    #     image: busybox
    #     container_name: busybox
    #     hostname: busybox
    #     network_mode: bridge
    #     restart: always
    #     # privileged: true
    #     # entrypoint:
    #     #   - top
    #     networks:
    #       - xiabook-net
   
    xiabook-mysql:
        image: mysql:8-oracle
        container_name: xiabook-mysql
        hostname: com.xiabook.mysql
        # network_mode: bridge
        networks:
         - xiabook-net
        ports:
         - "13306:3306"
        volumes:
         - ./mysql/data:/var/lib/mysql
         - ./mysql/conf:/etc/mysql/conf.d
         - ./mysql/init/:/docker-entrypoint-initdb.d
        user: mysql
        command:
            # 将mysql8.0默认密码策略 修改为 原先 策略 (mysql8.0对其默认策略做了更改 会导致密码无法匹配)
            --default-authentication-plugin=mysql_native_password
            --character-set-server=utf8mb4
            --collation-server=utf8mb4_general_ci
            --explicit_defaults_for_timestamp=true
            --lower_case_table_names=1
        environment:
         - tz=Asia/Shanghai
         - MYSQL_ROOT_PASSWORD=123456
         - MYSQL_DATABASE=smf-book
         - MYSQL_USER=xiaobook
         - MYSQL_PASSWORD=123456

    xiabook-redis:
        image: redis:alpine3.16
        container_name: xiabook-redis
        hostname: com.xiabook.redis
        # network_mode: bridge
        networks:
         - xiabook-net
        command: redis-server /etc/redis/redis.conf --requirepass 123456
        volumes:
         - ./redis/redis.conf:/etc/redis/redis.conf
         - ./redis/data:/data
        ports:
         - "16379:6379"

    xiabook-puppeteer:
        image: xiabook/puppeteer-alpine:v1.0.2
        container_name: xiabook-puppeteer
        hostname: com.xiabook.puppeteer
        # network_mode: bridge
        networks:
         - xiabook-net
        ports:
         - "18088:8088"

    xiabook-server:
        image: xiabook/server:v1.0.8
        container_name: xiabook-server
        hostname: com.xiabook.server
        env_file:
          - xiabook.env
        depends_on:
          - xiabook-mysql
          - xiabook-redis
          - xiabook-puppeteer
        # build:
          # context: ../xiabook-server
          # dockerfile: Dockerfile
        volumes:
         - ./books:/runtime/books
        ports:
         - "3000:3000"
        networks:
         - xiabook-net

    xiabook-client:
        image: xiabook/client:v1.0.5
        container_name: xiabook-client
        hostname: com.xiabook.client
        # build:
        #   context: ../xiabook-client
        #   dockerfile: Dockerfile
        depends_on:
          - xiabook-server
        environment:
          - XIABOOK_SERVER_HOST=com.xiabook.server
          - XIABOOK_SERVER_PORT=3000
        ports:
         - "9000:9000"
        networks:
         - xiabook-net

networks:
  xiabook-net:
    name: xiabook-net